### ISSUE TITLE
Player home Mona Alta inaccessible 

### ISSUE THREAD

**Issue by D-Lemons** [ForgottenGlory/Living-Skyrim-3#114]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 3

**Describe the bug**
Mona Altas entrance is completely blocked by a mountain.

**To Reproduce**
Go to Mona Alta north of Illinaltas Deep

**Expected behavior**
A usable home.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![SkyrimSE 2021-02-10 02-07-58-min](https://user-images.githubusercontent.com/70304489/107610172-40535380-6bfe-11eb-9240-917d2b902afa.png)

**Additional context**

**Comment by JaxomofRuatha** [comment]
So I looked into this, and two things seem to be going on. The exterior shot from the screenshot seems to more or less be correct (from what I'm seeing in other people's reviews of the mod), but might be some clipping issues.

The more critical pieces are:

1.) The boulders blocking the stairway leading up, which are because of Skyrim 3D Rocks. Disabling that mod removes that problem, but most likely we can get rid of it with a CK patch.

2.) There are invisible walls around some of the land, including at the end of the stairway leading to the Path of Faith (which is how you actually are supposed to get across to the home). That seems to be caused by Majestic Mountains from what I can tell, but I'm not entirely sure how to patch that out while keeping MM in. Again I'm assuming that some CK work will be needed.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
