### ISSUE TITLE
Daedra Venin alchemy ingredient

### ISSUE THREAD

**Issue by jwildy** [ForgottenGlory/Living-Skyrim-3#168]
**LS Version**
3.0.0.4 (Beta 4)

**Describe the bug**
Eating Daedra Venin knocks the player over, and upon standing up breaks the camera. It switches to 3rd person, and locks the camera in a spot. you cant change it to first person or move it. Also Daedra Venin has no active effects that show in the Magic Active Effects tab.

**To Reproduce**
Eat Daedra Venin

**Expected behavior**
Learn about the alchemical properties of Daedra Venin

**Additional context**
Tried eating in while is both first and third person camera. happened in both situations.

**Comment by TheCampingOwl** [comment]
ID 780CB2B2
Ref FF001079
Complete alchemy & cooking overhaul

Issue is specific to Daedra Venin, no other item that gives "Paralysis" will have the same problem, it's also a reported issue on the mod author page since jan 30th, no updates from author on the issue as of yet. A user reported he fixed it by eating an item that counteracts paralysis.

We've tried to repeat this process, the problem is still there. Smoothcam was disabled, no change. Problem is specific to what the Daedra Venin item does to skyrims camera.

As an additional note: This camera bug is from vanilla skyrim, granted it is rare as hell, but it does happen. This item seems to trigger that bug every time.

**Comment by TwistedModding** [comment]
Disabling ragdoll paralysis within the Complete Alchemy and Cooking Overhaul MCM fixes this issue.

**Comment by ForgottenGlory** [comment]
Done
