### ISSUE TITLE
Reading is Good not working with Xarxes from Wintersun

### ISSUE THREAD

**Issue by jwildy** [ForgottenGlory/Living-Skyrim-3#182]
**LS Version**
3.0.0.5 (Beta 5)

**Describe the bug**
Reading Is Good gives 4% insight per skill book. Xarxes gives double skill points when reading a skill book while praying. So reading a skill book while praying should give 8% and it is only give 4%.

**To Reproduce**
Be a follower of Xarxes, pray and read a skill book. You can check your insight levels in the MCM under "Reading Is Good" to see where you are before and after reading. I have multiple skills at 4% even though I've prayed while reading all my skills books so far.

**Expected behavior**
Double the insight gained from reading skill books while praying as a follower of Xarxes.

**Comment by TwistedModding** [comment]
So I understand this is technically a "bug" I don't entirely think it would be balanced to get an 8% permanent  learning boost to a skill for just reading a skill. Two levels in a skill and a permanent 8% xp boost to that skill tree are completely different and therefore can't really be compared or simplified to "i should get 8% instea of 4% because wintersun says it gives two levels instead of one.

That's my thought on it, but it's up to @ForgottenGlory if he A, wants to leave it alone, or B, modify the xp bonus to maybe 6% from 4% when following xarxes. I personally think it should just be left alone.

**Comment by jwildy** [comment]
I agree, I think a better fix is to have Xarxes do something else, but I'm not sure how/if that is a possible change to make. I assume the 4% -> 8% change would be easier because Reading is Good already does something like that when you have the Scholar's Insight ability from Black Book: The Winds of Change.

**Comment by jwildy** [comment]
Or even better, you could base the Discovering Location XP off of the amount of favor you have built up so it falls in line with alot of the other Wintersun Deities.

**Comment by ForgottenGlory** [comment]
> C, we couldnt change it even if we wanted to because the way either mods are made

This one.

**Comment by jwildy** [comment]
ahh okay. sorry i know absolutely nothing about modding and how it works. kinda put my foot in my mouth with the suggestions.
