### ISSUE TITLE
Transition from LOD grass to normal grass

### ISSUE THREAD

**Issue by Schnipserle** [ForgottenGlory/Living-Skyrim-3#209]
**LS Version**
3.0.0

**Describe the bug**
The distant LOD grass texture looks greyish. It changes to normal texture color as soon as you get close enough.
Clean install with Rudy ENB.

**To Reproduce**
Everywhere in Tamriel. Very noticeable near Whiterun stables.

**Expected behavior**
Similar distant LOD grass color.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/67802820/110048156-92941a00-7d4f-11eb-8982-64e4384346d3.png)

**Additional context**

Similar problems are reported on Folkvangr Nexus page. Perhaps you can tweak the colors before generating grass LOD.

![grafik](https://user-images.githubusercontent.com/67802820/110048352-ffa7af80-7d4f-11eb-9f9b-1c4b7e48396f.png)

**Comment by TwistedModding** [comment]
That's a pretty good find, I'll give this a go.

**Comment by TwistedModding** [comment]
So those settings help out the issue a little bit, but it's definitely not the end all be all settings. I would suggest holding off on redoing the lods (for this purpose only) until better settings get posted.

**Comment by TwistedModding** [comment]
After further investigation, the grass lod texture heavily depends on which enb you're using. The issue is definitely still noticeable without an enb, but results will vary from enb to enb. Meaning this is *technically* unfixable. I'm trying to find feasible settings for the enb I use (rudy enb), and once I do find them, I'll post them here.
