### ISSUE TITLE
(Bard) Options in Taverns Soft-locking saves

### ISSUE THREAD

**Issue by se7enex** [ForgottenGlory/Living-Skyrim-3#247]
I've only had this issue with Ange (havent tried others) but if you use the (bard) option in dialogue to perform a song with her nothing happens, you get frozen in place for eternity and have to reload an earlier save. 

I've only tried it with Ange so far but it's repeatable through multiple playthroughs.

**Comment by Eurafrica** [comment]
Can confirm this happening with Ange as well. There's no way out once you click on a perform-with-her option.

**Comment by ForgottenGlory** [comment]
I seem to recall there being an issue with Ange previously, Open to suggestions on how to fix this.

**Comment by celadoneiron** [comment]
I had a look into this. Sometimes it CTDs instead, which is fun. But based on what I've found in the comments on the Nexus page, it's an issue with using the BSA version rather than the Loose Files version - something with the audio compression makes things stop working and can cause game crashes. We're also several versions behind the most recent one.

In my brief testing, once I installed the latest Loose Files version and the additional hotfix update file, asking Ange to play a song with me no longer caused a CTD or a softlock. However, there was still a bit of weirdness, because every time I asked her to play "A Warrior's Life," she did her part of the song while my character stood motionless, and then once she was done and walking away my character took out a flute and tootled solo for a bit. The other song, "Portraiture," had my character start at the same time, but continue for a couple of seconds after Ange had finished and started sandboxing again.

So updating and using the loose files version seems to fix the CTD (which apparently also sometimes happens with other 3DNPC bards and applies to their solo singing as well) and the softlock, but if the desync between NPC and player performance is going to be consistent, the easiest thing to do might be simply to disable the "(Bard) How about we play together?" dialogue option for the player entirely. You can still access almost all of the songs by asking them to perform solo.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
