### ISSUE TITLE
CTD when trying to load save.

### ISSUE THREAD

**Issue by Dvineownage** [ForgottenGlory/Living-Skyrim-3#250]
**LS Version**
3.0.0

**Describe the bug**
When I go to load any recent save (Quick, Auto, or Manual) I get a CTD.

**To Reproduce**
Unknown.

**Expected behavior**
Load into the game as normal.

**Additional context**
From the late save I can successfully load to the latest save made I completed the Under Saarthal quest, and Geirmund's Hall dungeon. I then went to Reachwater Rock to finish Forbidden Legend quest.

[Crashlog.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6136147/Crashlog.zip)
[Working Save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6136151/Working.Save.zip)
[Failing Save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6136152/Failing.Save.zip)
[Auto and Quick save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6136156/Auto.and.Quick.save.zip)
[Autosaves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6136153/Autosaves.zip)

**Comment by Hanhula** [comment]
I've also been having this issue, though on 3.0.1 and in different context. https://pastebin.com/hC24QKSf I'm around level 10, joined the College of Winterhold and the Thieves Guild. The issue didn't seem to begin until past the latter, as I previously solved the issue by  just rolling back to a previous (manual) save. However it's now resumed being a problem, same as OP. 

I'll note my crashlogs from the previous time this was an issue have some slightly different errors in them. https://pastebin.com/pxwD8J8D  Here's one.

**Comment by celadoneiron** [comment]
I think this and #245 are the same bug, and both caused by Haafinheim. The working saves that Dvineownage and Bellmerser provided both show the same kind of warning when trying to open in ReSaver:

"Potential problems were identified
There are 14 stacks and 62002 frames, which probably indicates a problem. wezArtistCreepy occurs the most often (61988 occurrences)
There is a stack 39516 frames deep (wezArtistCreepy (00229900) 39516 frames)."

The numbers are slightly different between the different saves, but the script in question, wezArtistCreepy, is the same. Here's a comment left on the Haafinheim Nexus page:

https://forums.nexusmods.com/index.php?showtopic=2654639/#entry56671731
> Hello! I seem to be having some save bloat issues stemming from this mod- perhaps someone can corroborate or comment:
> 
> It seems that script wezArtistCreepy is the cause my bloat issues. Looking at my save files using Save Tool, if more than one instance of this script is listed under Active Scripts, my save files begin to bloat. Clicking on any instance of wezArtistCreepy crashes save tool. I believe this script has something to do with the despawn of the Artist ghost, as I could resolve the bloat each time by returning to Haafinheim, finding the Artist, and watching him vanish. I have to do this twice: re-entering the cell to find him a second time, though one time I entered to find two iterations of the Artist despawn in the same vicinity.
> I've compared saves before and after in terms of size and active threads (using Papyrus Data Transfer), and undoubtedly this event resolves a significant amount of bloat. In my first investigation, I instantly shaved off 10mb from my save, and the active thread count went down from an astronomical 37000, to 1.
> 
> I don't know what could be causing this script to 'stick' twice, and it obviously doesn't happen all the time, as I've visited Haafinheim frequently without inducing bloat. Might be a peculiarity of my load order, but I figured I should bring it up and see if others have any comment. Any help or advice would be much appreciated :)
> 
> It's a beautiful home, but I'm considering a (risky?) mid-game uninstall since it seems to be behaving oddly in my particular case. 

Both saves take substantially longer to load in ReSaver than normal saves, and multiple users with saving issues are reporting that saving takes a long time, progressively longer than normal as they go on. This is consistent with my experience of saves where a script is acting up and doing this thing with tons of stacks of tons of frames.

The saves that CTD are impossible for ReSaver to open, getting the error "Error while reading file [name of save file]. Position mismatch; counted 58007 but actual 58007 in [name of save file]." (Even though it says they're a mismatch, within each error message/individual save file, the two numerical values are actually exactly the same, although across the different save files they're different.)

I think we need to yeet Haafinheim from the next release. While entering the home and watching the ghost disappear again, or just deleting the script instances from the save file, may be a temporary fix, it can't help restore saves that CTD because those can't be loaded with ReSaver in the first place.

**Comment by Dvineownage** [comment]
Yup I did do that quest, although I don't use the house.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
