### ISSUE TITLE
CTD when trying to enter the world "open Skyrim zone"

### ISSUE THREAD

**Issue by jhgh1** [ForgottenGlory/Living-Skyrim-3#253]
Hi,

I managed to install the 3.0 list and follow all the points in the official guide (Only not changing the original Skryim SE install outside of the default Steam folder)

The game lunches fine and I can get to the starting room with the statue to chose the default start.
I can select something like starting with a land. And I spawn and can play inside that house.
The problem is that when I try to "enter Skyrim zone" or for example Solitude if I pick that home, leaving the house the game CTD.

What can cause LS 3.0 to CTD when exiting the starting house? If I select a start in the Skyrim world, the game CTD.
[Crash_2021_3_14_14-36-24.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6136857/Crash_2021_3_14_14-36-24.txt)

Thanks!

**Comment by jhgh1** [comment]
EDIT: Doing some testing and using the included BethINI.exe I managed to get a working start. 

Seems like this is an hardware / driver settings problem.

Feel free to delete / close this.

Thanks

**Comment by celadoneiron** [comment]
> and follow all the points in the official guide (Only not changing the original Skryim SE install outside of the default Steam folder)

You need to follow the installation instructions to the letter - we don't tell you to change the location of your Skyrim SE install folder because we think it's fun to do, it's important for getting the list to work correctly.

**Comment by TwistedModding** [comment]
this crash is due to memory.
follow these instructions to fix it:

Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:
1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.
