### ISSUE TITLE
Reoccurring crash to desktop 

### ISSUE THREAD

**Issue by ashair12** [ForgottenGlory/Living-Skyrim-3#288]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.
[save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6247243/save.zip)

**LS Version**
V3.1.0

**Describe the bug**
Crash to desktop when entering Solitude. 

**To Reproduce**
I saved before entering a new instance (as I always do), entered gates of Solitude and the game crashed to desktop before the loading screen appeared.

**Expected behavior**
Enter Solitude.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
This is a reinstall of LS3 as I was getting CTD's when entering instances after about ~30 mins of gameplay. I used Skyrim shredder and followed every word of the readme. Not sure what's causing the issue. This was the longest I have gone without a CTD on a brand new character, about two hours of gameplay.

**Comment by TwistedModding** [comment]
post some crashlogs Please upload (drag and drop the file into this channel) the most recent crash log from your [LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash folder. The Files Generated folder can be found near the bottom of MO2's left pane.

**Comment by ashair12** [comment]
Hey, I already attached the crash log in the save.zip file. Here it is again:
[Crash_2021_4_1_21-34-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6247612/Crash_2021_4_1_21-34-14.txt)

**Comment by ashair12** [comment]
> post some crashlogs Please upload (drag and drop the file into this channel) the most recent crash log from your [LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash folder. The Files Generated folder can be found near the bottom of MO2's left pane.

**Comment by TwistedModding** [comment]
Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:

1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.
