### ISSUE TITLE
Black Screen when loading in to Whiterun (Sometimes)

### ISSUE THREAD

**Issue by Jzenner615** [ForgottenGlory/Living-Skyrim-3#316]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Newest Version (3.1.1)

**Describe the bug**
When I am loading into Whiterun I will get a black screen after the loading screen (I can hear the audio too), the only way to resolve this is to close out of the game and then reload a save to before I entered Whiterun. Sometimes it will allow me to enter without any issues.

**To Reproduce**
Enter Whiterun.

**Expected behavior**
I expect to load in without any issues.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by scraunch** [comment]
I have been modding Skyrim for years. The infinite black screen with running water/noise in the background is just one of the caveats of playing modded Skyrim. It will happen on rare occasion. The fix is just as you describe; Close out of game and Reload your most recent save. It is a nuisance, but it is what it is. I played for 6 hours yesterday and had this happen to me entering the Jarls longhouse in Morthal, but just the 1 time.

**Comment by Jzenner615** [comment]
I managed to figure out a trick and ever since every time I load in perfectly, all I got to do is just go into third person before going into town and for some reason I don't get any issues.
