### ISSUE TITLE
Black Face Spotted 

### ISSUE THREAD

**Issue by Cerberus610** [ForgottenGlory/Living-Skyrim-3#32]
I was doing a quest and came across some bandits and one had a texture issue. 
![LS3](https://user-images.githubusercontent.com/78388153/106586935-ffc94b00-6516-11eb-82eb-07996658dffd.jpg)

**Comment by TwistedModding** [comment]
Select the npc in the console and post a screenshot or we cant do anything

**Comment by Cerberus610** [comment]
Ok , no Problem.  I'll try to look for it again and try that whem im off
monday. Thanks for the heads up

**Comment by TwistedModding** [comment]
*ahem*

**Comment by Darkangel13** [comment]
Hey there can you pls check if this fixes the issue pls.
[OrganicFactionFaceFix.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5954416/OrganicFactionFaceFix.zip)

For me before:
![enb2021_2_9_22_41_30](https://user-images.githubusercontent.com/26364611/107432725-a9689780-6b28-11eb-9ba6-858a98139ac3.jpg)
after:
![enb2021_2_9_22_44_04](https://user-images.githubusercontent.com/26364611/107432740-af5e7880-6b28-11eb-8485-b1b478b1f608.jpg)

**Comment by Darkangel13** [comment]
It should fix bunch of dudes as well.

**Comment by Cerberus610** [comment]
I didnt find them last night but thats them ! Good find! 👌

**Comment by Darkangel13** [comment]
Do you have a save you can try the fix on?

**Comment by Cerberus610** [comment]
Yea , i do. Not where i saw them near morthal but I'll try again in a bit.

**Comment by Darkangel13** [comment]
@Devs the Base Form is 1700334B, base last changed by OrganicFactions.esm Sorry forgot to add that.

**Comment by Cerberus610** [comment]
I haven't found the "Exact" faction but the other custom forsworn faction
seem to be fine from what i see.

**Comment by celadoneiron** [comment]
This issue exists because the Organic Factions mod has its NPC facegen data in incorrectly-named folders - they're in /meshes/actors/character/facegendata/facegeom/OrganicFactions.esp and textures/actors/character/facegendata/facegeom/OrganicFactions.esp, but the game is looking for those strings to end with _.es**m**_ to match the file extension of the mod.

![SkyrimSE 2021-02-10 17-50-46](https://user-images.githubusercontent.com/73095714/107481497-ff414c00-6bc9-11eb-9cf7-f4a8cb4e18de.png)
^ Default

![SkyrimSE 2021-02-10 17-57-56](https://user-images.githubusercontent.com/73095714/107481554-1b44ed80-6bca-11eb-8a80-de40b4fd85e8.png)
^ With the folder names changed to end with .esm

I tested this on three other NPCs from OrganicFactions.esm with the same results.

**Comment by Cerberus610** [comment]
I've been playing for hours and hours and I've yet to come across them, nice find solution!

**Comment by ForgottenGlory** [comment]
Fixed Beta 3

**Comment by celadoneiron** [comment]
Confirmed present beta 3. See related issue #127.

![Screen Shot 02-12-21 at 09 13 PM](https://user-images.githubusercontent.com/73095714/107761753-9dbee000-6d77-11eb-8ba8-83db1249ff93.PNG)

Folder names should be:

Data\textures\actors\character\facegendata\facetint\OrganicFactions.esm
Data\meshes\actors\character\facegendata\facegeom\OrganicFactions.esm

Data\textures\actors\character\facegendata\facetint\OrganicFactionsExtension.esp
Data\meshes\actors\character\facegendata\facegeom\OrganicFactionsExtension.esp

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
