### ISSUE TITLE
Anoriath whiterun merchant elf hostile for no reason?

### ISSUE THREAD

**Issue by ganshunter** [ForgottenGlory/Living-Skyrim-3#332]
**LS Version**
v3.0.1

**Describe the bug**
Anoriath merchant elf in whiterun attacks me whenever he sees me.
**To Reproduce**
Walk in the centre of whiterun where he has his little place to sell stuff.

**Expected behaviour**
Not attacking the player without reason.

**Additional context**
Is this a bug or something within only my game?

**Comment by ChunkeeMunkee** [comment]
This is most likely related to a vanilla bug that becomes more prevalent in modded games.

Can you try opening the console up and clicking the aggressive character so that they turn white (hover the cursor over them and scroll the mouse wheel if you can't select them first try), and type:

paycrimegold 0 0

This should clear the issue for you.

**Comment by ganshunter** [comment]
> This is most likely related to a vanilla bug that becomes more prevalent in modded games.
> 
> Can you try opening the console up and clicking the aggressive character so that they turn white (hover the cursor over them and scroll the mouse wheel if you can't select them first try), and type:
> 
> paycrimegold 0 0
> 
> This should clear the issue for you.

Thank you! Worked like the charm.

**Comment by ChunkeeMunkee** [comment]
No problem at all - please feel free to jump onto the Discord if you run into any other issues (link in the ReadMe)
