### ISSUE TITLE
Dark Face Bug - Vantus Lorelius

### ISSUE THREAD

**Issue by echilda** [ForgottenGlory/Living-Skyrim-3#335]
**LS Version**
3.2

**Describe the bug**
Dark face on NPC Vantus Lorelius at Lorelius Farm near Whiterun

**To Reproduce**
Approach the NPC

**Expected behavior**
Face should not be dark

**Screenshots**
<img width="1920" alt="The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 05 05 - 23 05 04 90" src="https://user-images.githubusercontent.com/49254199/117215769-9e0acc80-adf6-11eb-90b6-d21c02f2cd35.png">

[The Elder Scrolls V  Skyrim Special Edition Screenshot 2021.05.05 - 23.05.04.90.png.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6430512/The.Elder.Scrolls.V.Skyrim.Special.Edition.Screenshot.2021.05.05.-.23.05.04.90.png.zip)
[The Elder Scrolls V  Skyrim Special Edition Screenshot 2021.05.05 - 23.05.24.72.png.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6430514/The.Elder.Scrolls.V.Skyrim.Special.Edition.Screenshot.2021.05.05.-.23.05.24.72.png.zip)

**Additional context**

**Comment by celadoneiron** [comment]
For Vantus Loreius specifically, Pride of Skyrim AIO has loose files from the Miscellaneous Males optional module that are overwriting the ones from Jampion NPCs. There's no .esp for the Miscellaneous Males module contained within the Pride of Skyrim AIO mod folder in LS3, which is why there aren't conflicts showing in xEdit.

There are about 50 other NPCs who will be affected by the loose Pride of Skyrim files.

I'll list two potential fixes in the developer bug hunting channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.1
