### ISSUE TITLE
Game Crashes on Save

### ISSUE THREAD

**Issue by soifua** [ForgottenGlory/Living-Skyrim-3#374]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
[Crash_2021_6_8_8-43-58.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6617936/Crash_2021_6_8_8-43-58.txt)
[Crash_2021_6_8_8-17-56.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6617938/Crash_2021_6_8_8-17-56.txt)
[Crash_2021_6_8_8-7-17.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6617939/Crash_2021_6_8_8-7-17.txt)
[Crash_2021_6_8_7-48-56.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6617941/Crash_2021_6_8_7-48-56.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.2.1

**Describe the bug**
Game crashes on save, either quick or full save

**To Reproduce**
1) Either hit F5 or save through the ESC menu
2) Game crashes

**Expected behavior**
Game should save and not crash

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
When I loaded up the game this morning, I choose one of the Shalidor missions. This one was in Markarth. I couldn't fast travel to either Markarth or the Underground Keep even though I had been to both previously. Calcelmo gave me the Nimhe mission again even though I had already completed it earlier. After I killed Nimhe, I tried to save the game and it crashed. I then tried to save in different situations and locations and had the result. These included after talking to Calcelmo and informing him that Nimhe was dead, after leaving the Understone Keep, and after fast traveling to the Lover's Stone.

**Comment by ForgottenGlory** [comment]
This is already fixed in 3.2.2. Update the list and start a new character to take advantage of the fix.

**Comment by soifua** [comment]
100+ hours into my first LS character. I'd prefer not to restart.

**Comment by ForgottenGlory** [comment]
Unfortunate.

**Comment by soifua** [comment]
This is my first experience using a modlist. Is this a regular thing, where bugs are fixed that require a new save?  Living Skyrim is stunning. I can appreciate the amount of time and effort that went into to creating it. And I don't want to have to restart again if I start a new save.

**Comment by PulsefireEzreal** [comment]
typically, when the bug fixing involves bugs that can ruin entire saves that aren't fixable mid-playthrough. Modlists are always being updated. There will always be bugs to fix until we no longer care to update the modlist. We're jam-packing 700+ mods into a game that is buggy AF in the first place. The dev/mod team spend hundreds of hours fine-tuning the list, to make it smooth and clean, but, as murphys law suggests, anything that can go wrong, will. We are releasing this for FREE. Meaning the only thing you spend, is your time. We didn't even know about this game-ending bug until about 4-5 days before we released the update. Simply because no one discovered it until then. And thats why we will always be bug-fixing. Because there will always be bugs that people encounter after having done something no one else has. It sucks you have to make a new save, i get it. Ive done it plenty of times myself, with over 500 hrs in ls2, and now over 200 hrs in ls3. We wont be fixing your game-breaking bug specifically because, the option to have it fixed is right there, starting a new character. We dont get paid for this mate. We spend our time finding and sorting out these bugs, so later on, in the future, the modlist gets ever so much closer to being more stable. You can complain about not being able to continue your "long" term save game, ive had longer, and thats honestly ok. Lets me try out different builds, and ideas, maybe do stuff differently the next time around. This isn't a company making a newer skyrim. This is just people who know how to code/mod, making a list of a stupidly large amount of mods so that others can enjoy them too. You can say, "that's stupid" thats fine. but dont be surprised when we tell you to buzz off. We owe no one anything. Nor do the players of the list to us.
