### ISSUE TITLE
Enchanting leveling for no reason

### ISSUE THREAD

**Issue by Gerdofal** [ForgottenGlory/Living-Skyrim-3#390]
**LS Version**
Most recent, freshly downloaded 7-1-2021. I think it's 3.2.2? Not sure.

**Describe the bug**
Enchanting has started leveling unexpectedly, possibly related to an item that I got from killing the Warlock in the cave when escaping in "Warlock's Thrall" alternate start. The weapon is a "Staff of Firebolts" from "Fulcimentum - More Staves and Wands of Skyrim". I noticed that I started getting enchanting skill via using the staff as soon as I got it. It has continued, I just got six or seven levels from one combat against a group of 8 foresworn. Enchanting has now leveled to 32 and I've never cast an enchanting spell.

**To Reproduce**
Use staff in combat, get enchanting skill. 

**Expected behavior**
I would expect that I should not get enchanting experience from using an item I looted.

**Screenshots**
![enb2021_7_2_23_42_41](https://user-images.githubusercontent.com/6471848/124347170-9a45bd00-db8f-11eb-8bad-99d3caa20bd2.png)

**Additional context**
I don't know if it's related, but the announcements about gaining enchanting levels came slowly after the combat, with maybe 20 seconds between them. That seemed a little long.

**Comment by Gerdofal** [comment]
Addendum I just Noticed Two Things:

The Skill is showing 32, but the most recent notification said enchanting had leveled to 12. So I've gotten 12 levels somehow by using the staff. Not quite as bad, but still weird.

Also, I went to double check what I saw and I see that the notifications are not in the Notification Log in the MCM. I don't know if that tells you anything, just thought I'd throw it out there to see if it might help.

**Comment by celadoneiron** [comment]
This is not a bug. This is a feature of the perk overhaul included in the list, Vokrii, which allows you to level Enchanting by using staves in combat. The difference between the two different skill levels is because you selected a Class from Classic Classes and Birthsigns that gives you a bonus to your Enchanting skill as a Fortify Skill effect. The notifications do not appear in the log because the messages that you get when you increase a skill are not delivered via the notification menu, they have their own specific part of the HUD menu that they fall under.

Please review the "Important Mods You Need To Know About" in the Living Skyrim readme, and follow the links to the mods in question to learn more about them.
