### ISSUE TITLE
ava and cc&br

### ISSUE THREAD

**Issue by TheMapzor** [ForgottenGlory/Living-Skyrim-3#408]
**LS Version**
3.3.0

**Describe the bug**
skills receiving boosts (from CC&BR i believe) do not appear to increase AVA attributes when leveled up

**To Reproduce**
I've been told about this issue from a friend, but not really having time for regular leveling right now, i attempted to reproduce it by console leveling (so i cannot confirm it doesn't work during regular gameplay). to reproduce via console, "player.incpcs skill" command will not allow gaining attributes when applied to skills affected by starting boosts, unless they are resetted to unboosted values by "player.modav -X", while it works normally on skills that do not have a starting bonus.

**Comment by Rahmiel** [comment]
First, off I'm not sure what you've written here makes sense, second off the boosts given by CC&BR are just that BOOSTS, not permanent to the base level of the skill. What I mean by that is, if the skill shows as being level 35 after being boosted by a class, it is actually only level 15, meaning you should NOT be getting an attribute from it. This is not a bug, this is literally how it is supposed to work.

I've made tons of characters and tested these mods specifically since building is one of my major niches in LS3.3 and can say without a doubt that you definitely still receive Attribute ups from skills that are boosted by classes picked under CC&BR. The only time you don't is if the BASE level of a skill is above 30 or 50 BEFORE you leave the Abandoned Prison (which you can only do using a glitch with the Reflect and CC&BR classes in a specific order I will not reveal here).

**Comment by TheMapzor** [comment]
Ava should give you an attribute at skill level 50 and 100 (so 70 and 120 in case of skills boosted by cc&br, or am I getting it wrong?) but it just doesn't, unless the skill value is corrected to -20 by console. I'm not aware of this glitch you're talking about, so I can't exclude that's what's causing the issue. I'll double check later this evening, but I'm confident every skill base level was 15 upon getting out of the prison.

**Comment by celadoneiron** [comment]
If every skill's base level was at 15, then something is wrong with your install, because LS3's starting base level for skills is 5, not 15 (and race + reflect bonuses are on top of that). Unless you boosted all of your skills before you left, they weren't all at 15.

If AVA is indeed using the modified skill value rather than the base skill value, this bug will only occur on one skill, and only if that skill is your race's most favoured skill (+15) _and_ you chose to reflect on that skill (+10) _and_ you chose it as one of your class skills (+20). That will bring you up to 50, and if the final boost that brings you to 50 isn't counted as the skill levelling up by the game and doesn't send the on-skill-level-up event, then you won't get the _first_ increase to that attribute. It should not stop you from receiving the second increase to that attribute at skill level 100, nor should it stop you from increasing attributes via other skills. If AVA is using the base skill value, you'll increase that attribute when your base skill level reaches the appropriate milestone. There's nothing unique about the CC&BR bonuses compared to other Fortify Skill effects.

Someone has raised an issue on the mod's Nexus page about skill bonuses possibly counting towards the necessary skill level for attribute increases, and the author has indicated they're looking into it.

**Comment by TheMapzor** [comment]
No boosting was done before leaving the prison. I'll do more tests later today and update with more details. Thank you for the explanation. (and yeah you are correct on level, I got confused with lv15 which was the baseline after the first legendary reset round).

**Comment by Rahmiel** [comment]
Okay then I correct myself, there is something odd happening here, because I'm definitely getting the Attributes when my skills (affected by the Class Bonus) hit level 30, which would make their bonus 50. I checked the mod page and it is supposed to be 50 and 100 not 30 and 50, which was confusing me because in my playthroughs it always seemed to be 30 and 50. I need to do more testing on this but I think there might actually be more of an issue here than I originally noticed because of my original mis-read of the mod.

**Comment by TheMapzor** [comment]
![Skyrim Special Edition 13_07_2021 23_36_29](https://user-images.githubusercontent.com/71673308/125529533-5a202e5b-1336-4efb-b39a-848c282918dd.png)
here are skill levels at moment of character creation (male breton)

![Skyrim Special Edition 13_07_2021 23_42_39](https://user-images.githubusercontent.com/71673308/125529594-f122db2f-124f-45ba-beb2-8f61b0ce3b25.png)
and here are the skill levels after ava, elsa and cc&br.

no skill boosting through console occurred yet, and i'm in the prison cell still (should i wait til i'm outside before using cc&br?).
boosts selected in cc&br were the 5 magic schools + speech (and they all get +20). reflect bonus i picked was sneak.

got out, leveled up to level 82, then fully leveled speech and illusion (the only two skills which affect the charisma attribute in ava, and incidentally, 2 skills affected by my cc&br boosting). cap level for them is 120. no ava attributes were given in the process.

i tried leveling up destruction (also affected by cc&br bonus), and no attribute given. same for conjuration. then i tried block, which i didnt assign any bonus to, and that works normally.

**Comment by TheMapzor** [comment]
tried installing the list on my laptop and could not reproduce the issue. reinstalled the list on desktop, and could not reproduce the issue again... i'm at a loss. asked my friend to reinstall the list again, and reset the skills on his own save, and level up by console again, and apparently he has no issues anymore either. the attributes are given normally upon hitting level 50 and 100 (cc&br bonus included) so i'm assuming we did something wrong (or something wrong happened anyway) on our main installations in the first place. so i think this can be closed. thanks for the help and sorry for wasting your time, silly me could have tried reinstalling right away.
