### ISSUE TITLE
CTD near Reachwater Rock

### ISSUE THREAD

**Issue by mikk198** [ForgottenGlory/Living-Skyrim-3#414]
LS Version
3.3.0

Describe the bug

Game crashes when going to get Jade Warrior 2 in Reachwater Rock. Crashed everytime i get near to Reachwater Rock. 
Tried to go there first vising Markarth but didnt change anything, still crash. No matter which way i tried.

To Reproduce
Just go there. 

Expected behavior
No crash.

[Crash_2021_7_16_19-37-11.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6833045/Crash_2021_7_16_19-37-11.txt)
[Crash_2021_7_16_20-3-27.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6833046/Crash_2021_7_16_20-3-27.txt)
[Crash_2021_7_16_20-16-31.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6833047/Crash_2021_7_16_20-16-31.txt)
[Crash_2021_7_15_19-11-28.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6833048/Crash_2021_7_15_19-11-28.txt)

**Comment by Rahmiel** [comment]
Also had the same issue 4 times in a row. I will only upload one of my logs to give an example.

I was able to circumvent the problem with a console command, specifically tai (toggleai). This needs to be done generally, meaning without having anything selected so as to disable ALL ai. This will prevent the crash allowing you to enter the area. I then used the console to kill all the Lost Valley Forsworn that spawn due to Organic Factions.

To note, an odd occurrence, even after using the tai command, which normally makes ALL actors in the game stand perfectly still and do absolutely nothing. Some of the forsworn and the two imperials that spawn at the camp continued fighting even though the AI was disabled. This leads me to believe there is a deeper issue with the mods involved here, specifically Organic Factions and possibly Increased Enemy Spawns, though I do not see the latter in every crash log.

[Crash_2021_7_18_18-45-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6837094/Crash_2021_7_18_18-45-5.txt)

**Comment by Sephiroth5000** [comment]
For me its the very same guys, but at the Markarth gates during their attack. Their original camp, at this moment it was filled with vanilla forsworn, didnt cause problems.
[Crash_2021_7_20_15-49-56.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6848963/Crash_2021_7_20_15-49-56.txt)

**Comment by Rahmiel** [comment]
Update about the fix. It is actually far simpler than I thought. Using TAI to enter the cell completely fixes the problem. Once the enemies load you can TAI again to start their AI and the game doesn't crash allowing you to fight them like normal. It would seem that whatever the issue is only happening when they first load into the cell.

**Comment by russel204** [comment]
I had a similar issue. Crashing as soon as i loaded the cell. Celadoneiron suggested the tcai toggle which did allow me to enter the cell and toggle it back on without crashing. I noticed a bit further on that there were a bunch of dead NPCs from a skirmish that were all standing around as if they were alive. and thought I should share that info on them as well. There were 10 or so dead NPCs from the skirmish. I've attached images of 1 from each faction involved. and a snippet of the map showing where it occurred. 
![actorInfo](https://user-images.githubusercontent.com/30775854/126884346-c7877e45-3a76-40ad-887b-85046052c292.png)
![actorInfo2](https://user-images.githubusercontent.com/30775854/126884349-d355c1a5-85b6-40bd-939d-baeeae051d04.png)
![location](https://user-images.githubusercontent.com/30775854/126884350-1e349348-c5e6-4867-b56e-58c928bfb1d7.png)

**Comment by russel204** [comment]
The requested Save file

Also, I should note that i have replaced two mods
Faster Mining Plus SE -> instant mining 
CC's enhanced ore veins SSE - 2k - 8.0 -> Glowing Ore veins 300 SSE

Instant mining
https://www.nexusmods.com/skyrimspecialedition/mods/687
Glowing Ore
https://www.nexusmods.com/skyrimspecialedition/mods/9147


[SaveFiles.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6873235/SaveFiles.zip)

**Comment by ForgottenGlory** [comment]
Rule 11
