### ISSUE TITLE
Nightvision doesn't work properly

### ISSUE THREAD

**Issue by SilimSavertin** [ForgottenGlory/Living-Skyrim-3#445]
**LS Version**
3.3.1

**Describe the bug**
Starting as a vampire, using the Nightvision power granted by being one either as a Power or via the hotkey from the Vision mod does not properly increase the ability to see in darkness. The borders of the screen get the slightly washed out effect that's supposed to happen.

**To Reproduce**
Create vampire character or become vampire, try to use Vampire's Sight power.

**Expected behavior**
Filter and enhanced light to actually be able to see in the dark.

**Screenshots**
https://imgur.com/SE85Bx2

**Comment by Zeronthe** [comment]
This is definitely related to the current ENB preset. Predator vision(which is what the enb was previously tuned for) was recently replaced with vision(the spiritual successor to it) without altering any of the ENB presets. 

A quick and dirty workaround would be to use the game's post processing in the ENB when using nighteye for now, but obviously visual fidelity may suffer as a result. Not really ideal, but the alternative is a ton of tweaking under the enbeffect.fx section of the enb to get it truly 100% fixed that i unfortunately don't have enough experience or patience with to really play around with fully.

**Comment by Zeronthe** [comment]
Can confirm the same issue.

This is likely due to the author dropping Predator Vision and replacing it with Vision and not updating their ENB preset at the same time. 

A temporary workaround is just using the game's post processing for now while you use nighteye, but it's kind of a hassle. And even then, it doesn't seem to be nearly as good as the old predator vision in my experience outside of the detect life features. Actually being able to see was the most important part.

**Comment by Rhone33** [comment]
The issue seems to be with Rudy ENB.  Night Vision seems to work fine if you disable ENB (shift-f12), and I also have it working fine under Silent Horizons ENB.  There are also posts on [Vision's Nexus page](https://www.nexusmods.com/skyrimspecialedition/mods/49943?tab=posts) from users reporting Vision not working with Rudy.

**Comment by ForgottenGlory** [comment]
This is going to be an issue with some ENB presets unfortunately. I am not aware of a way to fix it for all of them, I believe it's something the ENB preset creator has to implement.

**Comment by Zeronthe** [comment]
Some ENB presets? You're saying this like we're trying to use 3rd party unsupported ENBs(OP only did it as a workaround.) You'd kind of expect this to actually work with the ENB you ship with the list itself. It was working fine before the switchover from predator vision.

**Comment by celadoneiron** [comment]
It was working fine _for you_ before the switchover from Predator Vision. For many other users, Predator Vision did not function _at all,_ regardless of whether ENB was enabled or not. The spells and powers would straight up do nothing at all.

Yes, it is inconvenient that Rudy doesn't work out of the box with night vision. We're working on providing more options for users in terms of ENB and functionality. Still, you can toggle off ENB when trying to use night vision and it will work, which is an inarguable improvement over it not working under any circumstances.
