### ISSUE TITLE
gaming crashing 

### ISSUE THREAD

**Issue by bobjane01** [ForgottenGlory/Living-Skyrim-3#453]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
[
[Crash_2021_8_4_23-24-31.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6934755/Crash_2021_8_4_23-24-31.txt)
](url)

[Save29_60155766_0_547265766F72_Tamriel_000405_20210802025429_3_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6934767/Save29_60155766_0_547265766F72_Tamriel_000405_20210802025429_3_1.zip)

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.1

**Describe the bug**
crashing to desktop randomly 
**To Reproduce**
changing regions

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by TwistedModding** [comment]
Pagefile Settings
Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:

1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.

this should fix your crash. post more logs if it doesnt
