### ISSUE TITLE
Ring of Jurgen Windcaller won't reforge into the ancient version.

### ISSUE THREAD

**Issue by BigChungusFungus** [ForgottenGlory/Living-Skyrim-3#588]
**LS Version**
Living Skyrim 3.6.0.2

**Describe the bug**
The Ring of Jurgen Windcaller (Located in the Ustevgrav Depths) won't reforge into in the ancient version. (Link: https://legacy-of-the-dragonborn.fandom.com/wiki/Ring_of_Jurgen_Windcaller)

**To Reproduce**
There were no clear things I did that led to this bug.

**Expected behavior**
Described in the "Describe the bug" section.

**Screenshots**
Non-Applicable.

**Additional context**
Nope.

**Comment by thehajo** [comment]
Did you fulfill all the conditions? You need to:
1.) Have no armor equipped
2.) Have both hands free
3.) Have the Unrelenting Force shout equipped
4.) Be at the Skyforge
Because it did work for me while testing as you can see here:
![grafik](https://user-images.githubusercontent.com/38141473/141390520-95f4eaa8-91ab-4f80-9699-48dfabd8757f.png)

**Comment by TwistedModding** [comment]
reopen if the issue persists
