### ISSUE TITLE
Draugr unable to kill me at level 4

### ISSUE THREAD

**Issue by TheWorldiMap** [ForgottenGlory/Living-Skyrim-3#651]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.7.1

**Describe the bug**
Unsure if bug but level 18 draugr  doing less damage than bandits to the point where i can passively outheal their damage at level 4

**To Reproduce**
Get attacked by draugr in the angarvunde dungeon quest

**Expected behavior**
The Draugr should be able to kill a level 4 player as referenced in the living skyrim instillation guide i should not be able to kill undead until at least level 15 but they can't even damage me 

**Screenshots**
damage taken after being hit with greatsword 
https://cdn.discordapp.com/attachments/690613668836016178/940756323396636692/unknown.png

Enemy Draugr stats
https://cdn.discordapp.com/attachments/690613668836016178/940757864497184778/unknown.png

**Additional context**

[Save51_A1A953FD_0_54574D_Angarvunde02_000757_20220208233637_5_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/8028391/Save51_A1A953FD_0_54574D_Angarvunde02_000757_20220208233637_5_1.zip)

**Comment by Dace617** [comment]
I have checked your Saves. 
Based on your AVA stats of 18 Fortitude and 14 endurance, coupled with your full set of heavy armour giving you around 200 armour rating, as well as you being a werewolf with werewolf health regeneration and an effective Heavy Armour skill of 55 buffed with class abilities I believe this to be expected behaviour for the stats you have. 

I've been able to remove all your armour and have been killed with a couple of attacks from dragur in the area you are in.

If you don't want to restart and make a character again I can only suggest raising the game difficulty so that enemies do more, and you deal less damage.
