### ISSUE TITLE
Nettlebane replica mismatch

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Living-Skyrim-3#694]
Is bug?: Confirm

Read the readme?: Confirm

List Version: LS 3.8.4

Reproducable?: Yes

Discord Username: thorkellthetall#5431

Rule 11?: No

Type: Crafting

Summary: Nettlebane replica mismatch

Details: The Nettlebane (Replica) model as crafted at a replica station is a different model than the one you acquire in its given quest. Also, only the Replica is accepted when manually attempting to display Nettlebane. Attempting to manually display the true Nettlebane will read that you lack the required item. I have completed the quest with the sapling ending. Intended?

Steps to reproduce: 

Crash log: 

Screenshots:

**Comment by thehajo** [comment]
**Cannot** confirm the LOTD placement bug. Both the Replica and the Normal version were accepted for me. Here is a video:

https://user-images.githubusercontent.com/38141473/168682757-6d3a9e61-96b3-4970-9312-9d8287563811.mp4

The different texture is due to the default texture getting replaced by ArteFakes. If a patch is *really* necessary is another thing.

**Comment by thehajo** [comment]
**Cannot** confirm the placement bug. Video:

https://user-images.githubusercontent.com/38141473/168683254-952127e4-e0bc-4776-9838-2ae874865134.mp4

Texture mismatch is due to ArteFakes replacing the default look. If a patch is necessary is another thing.
