### ISSUE TITLE
replica's able to be crafted without obtaining original first

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#70]
**LS Version**
LS3 Beta 2

**Describe the bug**
replica's for the LoTD are being able to be crafted without obtaining the original first
**To Reproduce**
go to smith

**Expected behavior**
obtain original piece of gear to unlock replica smithing
**Screenshots**
![enb2021_2_6_02_34_46](https://user-images.githubusercontent.com/68168803/107106530-0fe96f00-6824-11eb-81bf-398bc63d22bd.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
I don't believe this can be fixed unless someone knows of one. Honed Metal pulls from the list of all craftable objects, so short of removing them from being craftable entirely I don't think we can do anything about it.

**Comment by celadoneiron** [comment]
Confirmed in beta 3, this issue exists in player crafting and is not limited to the Honed Metal commission menu. Replicas should, generally speaking, not be possible to craft except at the LOTD replica-specific stations for items that the player has previously had access to.
![Screen Shot 02-12-21 at 07 55 PM 001](https://user-images.githubusercontent.com/73095714/107756675-48330500-6d70-11eb-9612-5b26d167d9e3.PNG)

Possibly an automated patcher designed to make crafting recipes more consistent has removed LOTD's conditions that prevent the recipe from being visible until the appropriate quest has been completed/items have been held?

**Comment by celadoneiron** [comment]
This seems to be happening because one of the automated patchers has generated _new_ crafting recipes in the Synthesis.esp for all kinds of items that have conditions on their creation. These can't be detected via conflict checks because they're entirely new records, but that's the cause. Some of the new crafting recipes enable crafting of test items or NPC-exclusive items, e.g.:

![Screen Shot 02-12-21 at 10 03 PM 001](https://user-images.githubusercontent.com/73095714/107765797-29d40600-6d7e-11eb-9c12-66f8d3b21ba9.PNG)

Synthesis.esp is also where the incorrect crafting material requirements from #129 are being set.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
