### ISSUE TITLE
Crashes to desktop in some areas

### ISSUE THREAD

**Issue by cwwoodsy** [ForgottenGlory/Living-Skyrim-3#84]
I am getting random, but predictable crashes at certain points in the game world. I'm not sure if they are all related to each other, but there seems to be a border I can't cross with each one of them - instant crash to desktop. One of the areas is immediately outside of Whiterun - I can't approach the city. I can't even get quite to the fortified fork in the road just outside.

I've attached the latest crash log. Thanks!

[Crash_2021_2_7_15-20-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5939897/Crash_2021_2_7_15-20-47.txt)

**Comment by ForgottenGlory** [comment]
Your specific crash is fixed by this:

Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:
1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.

**Comment by cwwoodsy** [comment]
Hey, Thanks for taking the time out to respond! I manually set the pagefile for three drive to a minimum of 15GB and a maximum of 20GB. Skyrim and Living Skyrim are both installed on the C drive - a 500GB SSD. The other two drives are regular SATA HD's and are each 2TB. I restarted, jumped into my old save, and it still has the same issue. Any other suggestions? I have 64MB of RAM on the computer. Thanks!

**Comment by ForgottenGlory** [comment]
I hope you mean 64GB of RAM, because otherwise there's no helping.

**Comment by cwwoodsy** [comment]
LOL yes I do!

**Comment by ForgottenGlory** [comment]
In that case, I have no idea - the crash log indicates an out of memory error which is usually fixed by the pagefile issue. Hop into Discord if you're not already and we'll see what else we can do.

**Comment by cwwoodsy** [comment]
Will do - looking through my hardware and the requirements, could it possibly be the graphics card? It's a GeForce GTX 970. It has 4GB of memory. I've never had an issue with that to date... maybe a bit of a slower FPS on a few games, but maybe that could be contributing?

**Comment by cwwoodsy** [comment]
I've figured out how to get around this. It looks like it was the 'Nobel Skyrim Mod HD-2K' that was causing the crashes. It was a reproducible crash to the desktop in multiple locations, including when I would approach either Whiterun or Morthal (likely others as well that I hadn't tested). Once I disabled the mod, everything worked great! I know the graphics card wasn't quite what was on the requirements, but everything else worked great. It was on a computer for my daughter, so I really wanted to get it working :-)
